export const CHANGE_FLAG_TRUE = 'CHANGE_FLAG_TRUE'.toLowerCase()
export const CHANGE_FLAG_FALSE = 'CHANGE_FLAG_FALSE'.toLowerCase()
export const WHEN_MOUSE_ENTER = 'WHEN_MOUSE_ENTER'.toLowerCase()
export const WHEN_MOUSE_LEAVE = 'WHEN_MOUSE_LEAVE'.toLowerCase()
export const INIT_CROMBS = 'INIT_CROMBS'.toLowerCase()